# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee8

[depend]
plus
ee8-plus

[ini]

[lib]
lib/jetty-ee8-annotations-${jetty.version}.jar
lib/ee8-annotations/asm-@asm.version@.jar
lib/ee8-annotations/asm-analysis-@asm.version@.jar
lib/ee8-annotations/asm-commons-@asm.version@.jar
lib/ee8-annotations/asm-tree-@asm.version@.jar
lib/ee8-annotations/jakarta.annotation-api-@ee8.jakarta.annotation.api.version@.jar
