# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee9

[depend]
ee9-plus

[lib]
lib/jetty-ee9-annotations-${jetty.version}.jar
lib/ee9-annotations/asm-@asm.version@.jar
lib/ee9-annotations/asm-analysis-@asm.version@.jar
lib/ee9-annotations/asm-commons-@asm.version@.jar
lib/ee9-annotations/asm-tree-@asm.version@.jar
lib/ee9-annotations/jakarta.annotation-api-@ee9.jakarta.annotation.api.version@.jar
