# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee10

[depend]
ee10-plus

[lib]
lib/jetty-ee10-annotations-${jetty.version}.jar
lib/ee10-annotations/asm-@asm.version@.jar
lib/ee10-annotations/asm-analysis-@asm.version@.jar
lib/ee10-annotations/asm-commons-@asm.version@.jar
lib/ee10-annotations/asm-tree-@asm.version@.jar
lib/ee10-annotations/jakarta.annotation-api-@ee10.jakarta.annotation.api.version@.jar
