# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee11

[depend]
ee11-plus

[lib]
lib/jetty-ee11-annotations-${jetty.version}.jar
lib/ee11-annotations/asm-@asm.version@.jar
lib/ee11-annotations/asm-analysis-@asm.version@.jar
lib/ee11-annotations/asm-commons-@asm.version@.jar
lib/ee11-annotations/asm-tree-@asm.version@.jar
lib/ee11-annotations/jakarta.annotation-api-@ee11.jakarta.annotation.api.version@.jar
